USE UNIVER;

SELECT FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT, AVG(PROGRESS.NOTE) [Средняя_оценка]
FROM PROGRESS INNER JOIN  STUDENT
ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
INNER JOIN GROUPS
ON GROUPS.IDGROUP = STUDENT.IDGROUP
INNER JOIN FACULTY
ON FACULTY.FACULTY = GROUPS.FACULTY
WHERE FACULTY.FACULTY IN ('IT')
GROUP BY ROLLUP (FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT)


SELECT FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT, AVG(PROGRESS.NOTE) [Средняя_оценка]
FROM PROGRESS INNER JOIN  STUDENT
ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
INNER JOIN GROUPS
ON GROUPS.IDGROUP = STUDENT.IDGROUP
INNER JOIN FACULTY
ON FACULTY.FACULTY = GROUPS.FACULTY
WHERE FACULTY.FACULTY IN ('IT')
GROUP BY CUBE (FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT)


SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT, AVG(PROGRESS.NOTE) [Средняя_оценка]
FROM PROGRESS INNER JOIN  STUDENT
ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
INNER JOIN GROUPS
ON GROUPS.IDGROUP = STUDENT.IDGROUP
WHERE GROUPS.FACULTY IN ('IT')
GROUP BY GROUPS.PROFESSION, PROGRESS.SUBJECT
	UNION
SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT, AVG(PROGRESS.NOTE) [Средняя_оценка]
FROM PROGRESS INNER JOIN  STUDENT
ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
INNER JOIN GROUPS
ON GROUPS.IDGROUP = STUDENT.IDGROUP
WHERE GROUPS.FACULTY IN ('HTT')
GROUP BY GROUPS.PROFESSION, PROGRESS.SUBJECT


SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT, AVG(PROGRESS.NOTE) [Средняя_оценка]
FROM PROGRESS INNER JOIN  STUDENT
ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
INNER JOIN GROUPS
ON GROUPS.IDGROUP = STUDENT.IDGROUP
WHERE GROUPS.FACULTY IN ('IT')
GROUP BY GROUPS.PROFESSION, PROGRESS.SUBJECT
	UNION ALL
SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT, AVG(PROGRESS.NOTE) [Средняя_оценка]
FROM PROGRESS INNER JOIN  STUDENT
ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
INNER JOIN GROUPS
ON GROUPS.IDGROUP = STUDENT.IDGROUP
WHERE GROUPS.FACULTY IN ('HTT')
GROUP BY GROUPS.PROFESSION, PROGRESS.SUBJECT


SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT, AVG(PROGRESS.NOTE) [Средняя_оценка]
FROM PROGRESS INNER JOIN  STUDENT
ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
INNER JOIN GROUPS
ON GROUPS.IDGROUP = STUDENT.IDGROUP
WHERE GROUPS.FACULTY IN ('IT')
GROUP BY GROUPS.PROFESSION, PROGRESS.SUBJECT
	INTERSECT
SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT, AVG(PROGRESS.NOTE) [Средняя_оценка]
FROM PROGRESS INNER JOIN  STUDENT
ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
INNER JOIN GROUPS
ON GROUPS.IDGROUP = STUDENT.IDGROUP
WHERE GROUPS.FACULTY IN ('HTT')
GROUP BY GROUPS.PROFESSION, PROGRESS.SUBJECT


SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT, AVG(PROGRESS.NOTE) [Средняя_оценка]
FROM PROGRESS INNER JOIN  STUDENT
ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
INNER JOIN GROUPS
ON GROUPS.IDGROUP = STUDENT.IDGROUP
WHERE GROUPS.FACULTY IN ('IT')
GROUP BY GROUPS.PROFESSION, PROGRESS.SUBJECT
	EXCEPT
SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT, AVG(PROGRESS.NOTE) [Средняя_оценка]
FROM PROGRESS INNER JOIN  STUDENT
ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
INNER JOIN GROUPS
ON GROUPS.IDGROUP = STUDENT.IDGROUP
WHERE GROUPS.FACULTY IN ('HTT')
GROUP BY GROUPS.PROFESSION, PROGRESS.SUBJECT