USE UNIVER;
SELECT FACULTY.FACULTY, PULPIT.PULPIT, GROUPS.PROFESSION, SUBJECT.SUBJECT, STUDENT.NAME,
	Case
	when(PROGRESS.NOTE = 6)then 'רוסעü'
	when(PROGRESS.NOTE = 7)then 'סולü'
	when(PROGRESS.NOTE = 8)then 'גמסולü'
	else ''
	end NOTE
	FROM FACULTY JOIN GROUPS 
	ON FACULTY.FACULTY = GROUPS.FACULTY
	JOIN STUDENT
	ON STUDENT.IDGROUP = GROUPS.IDGROUP
	JOIN PROGRESS
	ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT AND
	PROGRESS.NOTE between 6 and 8
	JOIN SUBJECT
	ON SUBJECT.SUBJECT = PROGRESS.SUBJECT
	JOIN PULPIT
	ON PULPIT.PULPIT = SUBJECT.PULPIT
	ORDER BY PROGRESS.NOTE DESC