USE UNIVER;

SELECT PULPIT.PULPIT, FACULTY.FACULTY
FROM PULPIT, FACULTY
WHERE PULPIT.FACULTY = FACULTY.FACULTY
	AND
	FACULTY.FACULTY IN (SELECT PROFESSION.FACULTY FROM PROFESSION
		WHERE (PROFESSION.PROFESSION_NAME LIKE '%technologies%' 
			OR 
			PROFESSION.PROFESSION_NAME LIKE '%technology%'))

SELECT PULPIT.PULPIT, FACULTY.FACULTY
FROM PULPIT INNER JOIN FACULTY
ON PULPIT.FACULTY = FACULTY.FACULTY
	WHERE FACULTY.FACULTY IN (SELECT PROFESSION.FACULTY FROM PROFESSION
		WHERE (PROFESSION.PROFESSION_NAME LIKE '%technologies%' 
			OR 
			PROFESSION.PROFESSION_NAME LIKE '%technology%'))

SELECT DISTINCT PULPIT.PULPIT, FACULTY.FACULTY
FROM PULPIT INNER JOIN FACULTY
ON PULPIT.FACULTY = FACULTY.FACULTY
	INNER JOIN PROFESSION
	ON FACULTY.FACULTY = PROFESSION.FACULTY
		WHERE (PROFESSION.PROFESSION_NAME LIKE '%technologies%' 
			OR 
			PROFESSION.PROFESSION_NAME LIKE '%technology%')

SELECT AUDITORIUM, AUDITORIUM_TYPE, AUDITORIUM_CAPACITY
FROM AUDITORIUM a
WHERE AUDITORIUM = (SELECT TOP(1) AUDITORIUM FROM AUDITORIUM aa
		WHERE aa.AUDITORIUM_TYPE = a.AUDITORIUM_TYPE
				ORDER BY AUDITORIUM_CAPACITY DESC)
	ORDER BY AUDITORIUM_CAPACITY DESC

SELECT FACULTY.FACULTY
FROM FACULTY
WHERE NOT EXISTS (SELECT * FROM PULPIT
	WHERE FACULTY.FACULTY = PULPIT.FACULTY) 

SELECT TOP(1)
	(SELECT AVG(NOTE) FROM PROGRESS
		WHERE SUBJECT LIKE 'OAP') [нюхо],
	(SELECT AVG(NOTE) FROM PROGRESS
		WHERE SUBJECT LIKE 'DB') [ад],
	(SELECT AVG(NOTE) FROM PROGRESS
		WHERE SUBJECT LIKE 'KG') [ясад]
FROM PROGRESS

SELECT AUDITORIUM, AUDITORIUM_CAPACITY
FROM AUDITORIUM
WHERE AUDITORIUM_CAPACITY >=ALL(SELECT AUDITORIUM_CAPACITY FROM AUDITORIUM
										WHERE AUDITORIUM_TYPE LIKE '%B%')

SELECT AUDITORIUM, AUDITORIUM_CAPACITY
FROM AUDITORIUM
WHERE AUDITORIUM_CAPACITY >=ANY(SELECT AUDITORIUM_CAPACITY FROM AUDITORIUM
										WHERE AUDITORIUM LIKE '%2')
