USE UNIVER;

GO 
CREATE FUNCTION COUNT_STUDENTS(@faculty varchar(20)) returns int
AS BEGIN DECLARE @rc int = 0;
SET @rc = (SELECT COUNT(IDSTUDENT) 
		FROM STUDENT S JOIN GROUPS G
		ON S.IDGROUP = G.IDGROUP
		JOIN FACULTY F
		ON F.FACULTY = G.FACULTY
		WHERE F.FACULTY = @faculty);
RETURN @rc;
END;
GO

select FACULTY,   
dbo.COUNT_STUDENTS(FACULTY) 
from FACULTY;