USE [UNIVER]
GO

/****** Object:  UserDefinedFunction [dbo].[COUNT_STUDENTS]    Script Date: 31.05.2025 4:12:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER FUNCTION [dbo].[COUNT_STUDENTS](@faculty varchar(20) = NULL, @prof varchar(20) = NULL) returns int
AS BEGIN DECLARE @rc int = 0;
SET @rc = (SELECT COUNT(IDSTUDENT) 
		FROM STUDENT S JOIN GROUPS G
		ON S.IDGROUP = G.IDGROUP
		JOIN FACULTY F
		ON F.FACULTY = G.FACULTY
		WHERE F.FACULTY = @faculty AND G.PROFESSION = @prof);
RETURN @rc;
END;
GO


select DISTINCT F.FACULTY, G.PROFESSION,   
dbo.COUNT_STUDENTS(F.FACULTY, G.PROFESSION)
from FACULTY F JOIN GROUPS G
ON F.FACULTY = G.FACULTY;