USE UNIVER;

GO
CREATE FUNCTION FCTEACHER(@p char(20)) returns int
AS
BEGIN
	DECLARE @rc int = (SELECT COUNT(*) FROM TEACHER
	WHERE PULPIT = ISNULL(@p, PULPIT));
	RETURN @rc;
END;
GO

SELECT PULPIT, DBO.FCTEACHER(PULPIT)
	[Количество преподавателей] FROM TEACHER

SELECT DBO.FCTEACHER(NULL) [Всего преподавателей]