USE UNIVER;

-- 1
SET NOCOUNT ON;

DROP TABLE IMPLICIT_TRAN_TABLE;

SET IMPLICIT_TRANSACTIONS ON;
DECLARE @tmp CHAR;

CREATE TABLE IMPLICIT_TRAN_TABLE(k CHAR);

INSERT IMPLICIT_TRAN_TABLE VALUES ('a'), ('b'), ('c');

SET @tmp = (SELECT COUNT(*) FROM IMPLICIT_TRAN_TABLE);

PRINT 'Количество элементов таблицы: ' + @tmp;

COMMIT;

SET IMPLICIT_TRANSACTIONS OFF;


-- 2
BEGIN TRY
	BEGIN TRAN

	INSERT PULPIT(PULPIT, PULPIT_NAME, FACULTY) VALUES ('ISIT', 'Information Systems and Technologies', 'IT');
	DELETE PULPIT WHERE PULPIT = 'SE';

	COMMIT TRAN
END TRY
BEGIN CATCH 
	PRINT ERROR_MESSAGE();
	IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
END CATCH;

SELECT * FROM PULPIT; 


-- 3
DECLARE @POINT VARCHAR(32);

BEGIN TRY
	BEGIN TRAN
		UPDATE PULPIT SET PULPIT_NAME = 'Forest' WHERE PULPIT = 'LV';
		SET @POINT = 'p1' ;
		SAVE TRAN @POINT;
		INSERT PULPIT(PULPIT, PULPIT_NAME, FACULTY) VALUES ('SE', 'Software Engineering', 'IT');
		SET @POINT = 'p2' ;
		SAVE TRAN @POINT;
		COMMIT TRAN;
END TRY
BEGIN CATCH
	PRINT ERROR_MESSAGE();
	IF @@TRANCOUNT > 0
		BEGIN
		print 'Control point: ' + @POINT;
		ROLLBACK TRAN @POINT;
		COMMIT TRAN;
		END
END CATCH;

SELECT * FROM PULPIT;


-- 4

-- A
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRANSACTION
-------------------------- t1 --------------------
SELECT @@SPID, 'insert AUDITORIUM' N'Результат', * FROM AUDITORIUM
WHERE AUDITORIUM.AUDITORIUM = '412-1';
SELECT @@SPID, 'update AUDITORIUM' N'Результат', * FROM AUDITORIUM_TYPE 
WHERE AUDITORIUM_TYPE.AUDITORIUM_TYPENAME = 'Computer';

COMMIT; 
-------------------------- t2 --------------------

DELETE AUDITORIUM WHERE AUDITORIUM.AUDITORIUM  =  '412-1'; 
SELECT * FROM AUDITORIUM;


-- 5

SELECT * FROM AUDITORIUM
--A
SET TRANSACTION ISOLATION LEVEL READ COMMITTED 
BEGIN TRANSACTION 
SELECT COUNT(*) FROM AUDITORIUM WHERE AUDITORIUM_TYPE = 'LB-K';
-------------------------- t1 ------------------ 
SELECT COUNT(*) FROM AUDITORIUM WHERE AUDITORIUM_TYPE = 'LB-K';
-------------------------- t2 ------------------
UPDATE AUDITORIUM SET AUDITORIUM_TYPE = 'LK' WHERE AUDITORIUM = '409-2' 
COMMIT; 


-- 6

-- A ---
DELETE AUDITORIUM WHERE AUDITORIUM= '200-2'
UPDATE AUDITORIUM SET AUDITORIUM_NAME = '301-1' WHERE AUDITORIUM_NAME = '203-2'
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ 
BEGIN TRANSACTION 
SELECT AUDITORIUM_NAME FROM AUDITORIUM WHERE AUDITORIUM_TYPE = 'LB-K';
-------------------------- t1 ------------------  
-------------------------- t2 -----------------
COMMIT;
SELECT CASE 
		WHEN AUDITORIUM_NAME = '203-2' THEN 'Updated row' 
		ELSE ' ' 
	END AS 'Update check',
	case
		WHEN AUDITORIUM_NAME = '200-2' THEN 'New row' 
		ELSE ' ' 
	END AS 'Phantom check', AUDITORIUM_NAME 
FROM AUDITORIUM WHERE AUDITORIUM_TYPE = 'LB-K';

-- 7

-- A
 
DELETE AUDITORIUM WHERE AUDITORIUM = '418-2';
DELETE AUDITORIUM WHERE AUDITORIUM = '419-2';

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE 
BEGIN TRANSACTION 
DELETE AUDITORIUM WHERE AUDITORIUM_NAME = '418-2';  
INSERT AUDITORIUM VALUES ('418-2','LK', 90, '418-2');
UPDATE AUDITORIUM SET AUDITORIUM_NAME = '423-1' WHERE AUDITORIUM_NAME = '418-2';
SELECT AUDITORIUM_NAME FROM AUDITORIUM WHERE AUDITORIUM_TYPE = 'LK';	

-------------------------- t1 -----------------
COMMIT;
-------------------------- t2 ------------------ 	
SELECT AUDITORIUM_NAME FROM AUDITORIUM WHERE AUDITORIUM_TYPE = 'LK';


-- 8
DELETE AUDITORIUM WHERE AUDITORIUM = '413-2';
BEGIN TRAN
INSERT AUDITORIUM VALUES ('413-2','LK', 90, '413-2');
	BEGIN TRAN
	UPDATE AUDITORIUM_TYPE SET AUDITORIUM_TYPENAME='Lecture Hall' WHERE AUDITORIUM_TYPE='LK';
	COMMIT;
if @@TRANCOUNT=0 rollback;
SELECT
(SELECT count(*) FROM AUDITORIUM WHERE AUDITORIUM='413-2')'AUDITORIUM',
(SELECT count(*) FROM AUDITORIUM_TYPE WHERE AUDITORIUM_TYPENAME='Lecture Hall')'AUDITORIUM_TYPENAME'

DELETE AUDITORIUM WHERE AUDITORIUM='413-2'