USE UNIVER;

SELECT AUDITORIUM.AUDITORIUM_TYPE,
		MAX(AUDITORIUM.AUDITORIUM_CAPACITY) [MAX],
		MIN(AUDITORIUM.AUDITORIUM_CAPACITY) [MIB],
		AVG(AUDITORIUM.AUDITORIUM_CAPACITY) [AVG],
		SUM(AUDITORIUM.AUDITORIUM_CAPACITY) [SUM],
		COUNT(*) [COUNT]
FROM AUDITORIUM INNER JOIN AUDITORIUM_TYPE
ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
GROUP BY AUDITORIUM.AUDITORIUM_TYPE

SELECT *
FROM (SELECT CASE when NOTE between 4 and 5 then '4-5'
				when NOTE between 6 and 7 then '6-7'
				when NOTE between 8 and 9 then '8-9'
				else '0'
				end [Оценка], COUNT(*)[Количество]
		FROM PROGRESS GROUP BY CASE
				when NOTE between 4 and 5 then '4-5'
				when NOTE between 6 and 7 then '6-7'
				when NOTE between 8 and 9 then '8-9'
				else '0'
				end) as T
					ORDER BY CASE [Оценка]
					when '8-9' then 1
					when '6-7' then 2
					when '4-5' then 3
					else '0'
					end

SELECT ROUND(AVG(CAST(PROGRESS.NOTE as float(4))),2) [AVG],
		FACULTY.FACULTY,
		GROUPS.PROFESSION,
		GROUPS.YEAR_FIRST
FROM FACULTY INNER JOIN GROUPS
ON FACULTY.FACULTY = GROUPS.FACULTY
INNER JOIN STUDENT
ON GROUPS.IDGROUP = STUDENT.IDGROUP
INNER JOIN PROGRESS
ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
GROUP BY FACULTY.FACULTY,
		GROUPS.PROFESSION,
		GROUPS.YEAR_FIRST
ORDER BY ROUND(AVG(CAST(PROGRESS.NOTE as float(4))),2) DESC

SELECT ROUND(AVG(CAST(PROGRESS.NOTE as float(4))),2) [AVG],
		FACULTY.FACULTY,
		GROUPS.PROFESSION,
		GROUPS.YEAR_FIRST
FROM FACULTY INNER JOIN GROUPS
ON FACULTY.FACULTY = GROUPS.FACULTY
INNER JOIN STUDENT
ON GROUPS.IDGROUP = STUDENT.IDGROUP
INNER JOIN PROGRESS
ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE PROGRESS.SUBJECT = 'DB' OR PROGRESS.SUBJECT = 'OAP'
GROUP BY FACULTY.FACULTY,
		GROUPS.PROFESSION,
		GROUPS.YEAR_FIRST
ORDER BY ROUND(AVG(CAST(PROGRESS.NOTE as float(4))),2) DESC

SELECT ROUND(AVG(CAST(PROGRESS.NOTE as float(4))),2) [AVG],
		GROUPS.PROFESSION,
		PROGRESS.SUBJECT
FROM FACULTY INNER JOIN GROUPS
ON FACULTY.FACULTY = GROUPS.FACULTY
INNER JOIN STUDENT
ON GROUPS.IDGROUP = STUDENT.IDGROUP
INNER JOIN PROGRESS
ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
WHERE GROUPS.FACULTY IN ('IT')
GROUP BY GROUPS.PROFESSION, PROGRESS.SUBJECT
ORDER BY ROUND(AVG(CAST(PROGRESS.NOTE as float(4))),2) DESC

SELECT P1.SUBJECT, 
	(SELECT COUNT(*) FROM PROGRESS P2
		WHERE P2.NOTE = P1.NOTE AND
			P2.SUBJECT = P1.SUBJECT) [Количество студентов]
FROM PROGRESS P1
GROUP BY P1.SUBJECT, P1.NOTE
HAVING P1.NOTE = 9 OR P1.NOTE = 8
ORDER BY [Количество студентов] DESC